# MDP CONFIGURATIONS LOCATION:
mdp_conf_dir: /dip/conf


########################################

# CONSUL CONFIGURATIONS

########################################

ip: 9.8.8.8
port: 8500

########################################

spring_active: demo

########################################

# APL (es-sql-engine)

########################################

apl:
  # default: port: 8900
  port: 8900
  elasticsearch_configuration:
    - ip: 127.0.0.1
      port: 9300
      restport: 9200
    - ip: 127.0.0.1
      port: 9300
      restport: 9200
  # interval is time in millisecond
  datasource_refresh_interval: 300000

#############galaxy##################
galaxy:
  # default: port: 9999
  port: 9999
  es_config:
    - host: 127.0.0.1
      port: 9300
    - host: 127.0.0.2
      port: 9300
    - host: 127.0.0.3
      port: 9300
  kafka_config:
    - host: 127.0.0.1
      port: 6667
    - host: 127.0.0.2
      port: 6667
    - host: 127.0.0.3
      port: 6667
######################################

gateway:
  port: 111
  cluster_nodes: 127.0.0.1 
