- include_tasks: "config.yml"

- include_tasks: "setup-collect-agent.yml"

- name: Get exsisted containers
  register: existed_containers
  command: docker ps --all --format "{{ "{{" }}.Names{{ "}}" }}"
  when:
    - inventory_hostname in groups['mdp_node']

- name: Remove exsisted containers
  shell: docker rm -f {{ item }}
  with_items: "{{ container_names }}"
  when:
    - inventory_hostname in groups['mdp_node'] and
      item in existed_containers.stdout

- name: Ensure docker service is running
  systemd:
    state: started
    name: docker
  become: true
  when:
    - inventory_hostname in groups['mdp_node']

- name: Stop nginx server on deploy host
  systemd:
    state: stopped
    name: nginx
  ignore_errors: true
  become: true
  when:
    - (inventory_hostname in groups['mdp_node']) and
      (inventory_hostname in groups['yum_repo_server'])

- name: Load docker images
  shell: docker load < {{ mdp_docker_images_dir }}
  become: true
  when:
    - inventory_hostname in groups['mdp_node']

- include_tasks: "mdp-162-specific.yml"
  when: version == "1.6.2"
  ignore_errors: True