- name: Install collect-agent
  become: true
  yum:
    name: collect-agent
    state: latest
  when:
    - inventory_hostname in groups['collect_agent']

- name: Start collect-agent service
  systemd:
    name: "collect-agent"
    state: restarted
    daemon_reload: yes
  become: true
  when:
    - inventory_hostname in groups['collect_agent']
