- name: Restart elasticsearch service
  vars:
    service_name: "elasticsearch"
    service: "{{ elasticsearch_services[service_name] }}"
    elasticsearch_conf: "{{ elasticsearch_confs.results|selectattr('item.key', 'equalto', service_name)|first }}"
    elasticsearch_package: "{{ check_elasticsearch_package.results|selectattr('item.key', 'equalto', service_name)|first }}"
  service:
    name: "{{ service_name }}"
    state: restarted
  when:
    - action != "config"
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - elasticsearch_conf.changed | bool
      or elasticsearch_package.changed | bool