enable_ntp: false

# YUM repository config
enable_yum: false
yum_repo_server: 127.0.0.1
yum_repo_dir: /data/mdp/repo
yum_always_up: false
yum_repo_port: 80

# PIP repository conifg
enable_pip: false
pip_repo_server: 127.0.0.1

# package names
deltarpm_rpm_name: deltarpm-3.6-3.el7.x86_64.rpm
python_deltarpm_rpm_name: python-deltarpm-3.6-3.el7.x86_64.rpm
createrepo_rpm_name: createrepo-0.9.9-28.el7.noarch.rpm
libxml2_rpm_name: libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm
nginx_rpm_name: nginx-1.14.0-1.el7_4.ngx.x86_64.rpm
jdk_rpm_name: jdk-8u161-linux-x64.rpm

# ruby dependencies
ruby_gems_dir: /data/mdp/gem
ruby_server_port: 8808
ruby_gems_dir_remote: /data/mdp/gem
# 注意：复写、修改ruby_gems_list配置前请务必和维护ruby的开发人员沟通
ruby_gems_list:
  - msgpack-1.2.4.gem
  - cool.io-1.5.3.gem
  - yajl-ruby-1.3.1.gem
  - serverengine-2.0.6.gem
  - http_parser.rb-0.6.0.gem
  - sigdump-0.2.4.gem
  - tzinfo-1.2.5.gem
  - tzinfo-data-1.2018.4.gem
  - strptime-0.1.7.gem
  - faraday-0.15.0.gem
  - multipart-post-2.0.0.gem
  - excon-0.62.0.gem
  - dig_rb-1.0.1.gem
  - ipaddress-0.8.3.gem
  - ltsv-0.1.0.gem
  - oj-2.18.5.gem
  - multi_json-1.12.2.gem
  - httpclient-2.8.3.gem
  - polling-0.1.5.gem
  - thread_safe-0.3.6.gem
  - fluentd-1.0.2.gem
  - ruby-kafka-0.4.1.gem
  - fluent-plugin-kafka-0.6.4.gem
  - elasticsearch-5.0.4.gem
  - elasticsearch-api-5.0.4.gem
  - elasticsearch-transport-5.0.4.gem
  - fluent-plugin-elasticsearch-2.1.1.gem
