---
- name: create yum repo
  block:
    - name: copy and unzip repolist 
      unarchive: src={{ repolist_file }} dest={{ mdp_path }}
    - name: create repolist
      shell: |
        cd {{ mdp_path }}/repolist/repo
        rpm -ih --force deltarpm-3.6-3.el7.x86_64.rpm
        rpm -ih --force python-deltarpm-3.6-3.el7.x86_64.rpm
        rpm -ih --force libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm
        rpm -ih --force createrepo-0.9.9-28.el7.noarch.rpm
        createrepo {{ mdp_path }}/repolist/repo
        cd /etc/yum.repos.d; mkdir -p baseold; mv *repo baseold

    - name: Add multiple repositories into the aone file
      yum_repository:
        name: aone
        description: aone yum repo
        baseurl: file://{{ mdp_path }}/repolist/repo
        enable: yes
        gpgcheck: no
        
