- name: install docker dependencies
  block:
    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest
    - name: install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
    - name: install lvm2
      yum:
        name: lvm2
        state: latest
    - name: install docker-ce
      yum:
        name: docker-ce
        state: latest

- name: init docker-compose
  copy:
    src: "{{ docker_compose_dir }}"
    dest: /usr/local/bin/docker-compose
    mode: u+x

- name: start docker service
  service:
    name: nginx
    state: started