---
- name: prepare yum, pip repositories
  import_tasks: enable_repo.yml
  tags:
    - mdp-all
    - mdp-load-env
    - mdp-repo

- name: init system configs
  import_tasks: sys_configs.yml
  tags:
    - mdp-all
    - mdp-load-env
    - mdp-config

- name: setup ntp
  import_tasks: setup_ntp.yml
  tags:
    - mdp-all
    - mdp-load-env
    - mdp-config

- name: init java
  import_tasks: install_jdk.yml
  tags:
    - mdp-all
    - mdp-load-env
    - java

- name: init ruby
  import_tasks: install_ruby.yml
  tags:
    - mdp-all
    - mdp-load-env
    - ruby

- name: disable repo
  import_tasks: disable_repo.yml
  when: yum_always_up
  tags:
    - mdp-all
    - mdp-load-env
    - mdp-repo