---
- name: instal dependencies
  block:
    - name: install deltarpm
      yum: name={{ mdp_repo_dir }}/deltarpm-3.6-3.el7.x86_64.rpm
    - name: install python-deltarpm
      yum: name={{ mdp_repo_dir }}/python-deltarpm-3.6-3.el7.x86_64.rpm
    - name: install libxml2-python
      yum: name={{ mdp_repo_dir }}/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm
    - name: install createrepo
      yum: name={{ mdp_repo_dir }}/createrepo-0.9.9-28.el7.noarch.rpm
  become: true

- name: Load repository
  yum_repository:
    name: MDP
    description: MDP Repository
    file: mdp
    baseurl: file://{{ mdp_repo_dir }}
    gpgcheck: no
    enabled: yes
    priority: 1
  become: true

- name: Update yum cache
  shell: |
    createrepo {{ mdp_repo_dir }}
    yum clean all
    yum makecache
