kafka_package_name: kafka_2_5_3_0_37
kafka_enabled: true
kafka_port: 6667
kafka_zookeeper: "{% for host in groups['zookeeper'] %}{{ host }}:{{ zookeeper_client_port }}{% if not loop.last %},{% endif %}{% endfor %}"
kafka_heap_size: 8g
kafka_log_dir: /var/log/kafka