kafka_services:
  kafka:
    group: kafka
    package_name: kafka_2_5_3_0_37
    enabled: true

kafka_port: 6667
kafka_zookeeper: "{% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}:{{ zookeeper_client_port }}{% if not loop.last %},{% endif %}{% endfor %}"