---
- name: Create mdp config directory
  file:
    path: "{{ mdp_conf_dir }}/rbac"
    state: directory

- name: Updating rbac configs
  block:
    - name: update rbac configs
      template:
        src: "rbac/bootstrap-prod.yml.j2"
        dest: "{{ mdp_conf_dir }}/rbac/bootstrap-{{ spring_active }}.yml"
    - name: update rbac configs
      template:
        src: "rbac/bootstrap.yml.j2"
        dest: "{{ mdp_conf_dir }}/rbac/bootstrap.yml"
    - name: copy log4j2 configs
      template:
        src: "rbac/log4j2.xml"
        dest: "{{ mdp_conf_dir }}/rbac/log4j2.xml"
