---
- name: Updating docker-compose configs
  block:
    - name: update docker-compose configs
      template:
        src: "docker-compose/docker-compose.yml.j2"
        dest: "/root/docker-compose.yml"
