---
- name: Create mdp config directory
  file:
    path: "{{ mdp_conf_dir }}/scheduler"
    state: directory

- name: Updating scheduler-admin configs
  block:
    - name: update scheduler-admin configs
      template:
        src: "scheduler/bootstrap-prod.yml.j2"
        dest: "{{ mdp_conf_dir }}/scheduler/bootstrap-{{ spring_active }}.yml"
    - name: update scheduler-admin configs
      template:
        src: "scheduler/bootstrap.yml.j2"
        dest: "{{ mdp_conf_dir }}/scheduler/bootstrap.yml"
    - name: copy log4j2 configs
      template:
        src: "scheduler/log4j2.xml"
        dest: "{{ mdp_conf_dir }}/scheduler/log4j2.xml"
