---
- name: Create mdp config directory
  file:
    path: "{{ mdp_conf_dir }}/executor"
    state: directory

- name: Updating executor configs
  block:
    - name: update executor configs
      template:
        src: "executor/bootstrap-prod.yml.j2"
        dest: "{{ mdp_conf_dir }}/executor/bootstrap-{{ spring_active }}.yml"
    - name: update executor configs
      template:
        src: "executor/bootstrap.yml.j2"
        dest: "{{ mdp_conf_dir }}/executor/bootstrap.yml"
    - name: copy log4j2 configs
      template:
        src: "executor/log4j2.xml"
        dest: "{{ mdp_conf_dir }}/executor/log4j2.xml"
