---
- name: Create mdp config directory
  file:
    path: "{{ mdp_conf_dir }}/gateway"
    state: directory

- name: Updating gateway configs
  block:
    - name: update gateway configs
      template:
        src: "gateway/bootstrap-prod.yml.j2"
        dest: "{{ mdp_conf_dir }}/gateway/bootstrap-{{ spring_active }}.yml"
    - name: update gateway configs
      template:
        src: "gateway/bootstrap.yml.j2"
        dest: "{{ mdp_conf_dir }}/gateway/bootstrap.yml"
    - name: copy log4j2 configs
      template:
        src: "gateway/log4j2.xml"
        dest: "{{ mdp_conf_dir }}/gateway/log4j2.xml"
