---
- name: Create mdp config directory
  file:
    path: "{{ mdp_conf_dir }}/nginx"
    state: directory

- name: Updating nginx configs
  block:
    - name: create nginx report directory
      file: path={{ item }} state=directory
      with_items:
        - "{{ mdp_conf_dir }}/nginx/conf.d"
        - "{{ mdp_conf_dir }}/nginx/html/report"
        - "{{ mdp_conf_dir }}/../logs"
    - name: update nginx conf configs
      template:
        src: "nginx/conf.d/dip.conf.j2"
        dest: "{{ mdp_conf_dir }}/nginx/conf.d/dip.conf"
