---
- name: Config elasticsearch.yml
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.json"
    mode: "0600"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool

- name: Config elasticsearch jvm.options
  template:
    src: "jvm.options.j2"
    dest: "/etc/elasticsearch/jvm.options"
    mode: "0600"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
