---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/elasticsearch"
    state: directory
    mode: 0770
    recurse: yes
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ zookeeper_services }}"

- name: Config elasticsearch.yml
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.json"
    mode: "0600"
  become: true
  register: elasticsearch_confs
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  notify:
    - Restart elasticsearch service