- name: Install kafka
  become: true
  yum:
    name: "{{ kafka_package_name }}"
    state: latest
  when:
    - inventory_hostname in groups['kafka']
    - kafka_enabled | bool

- include_tasks: config.yml

- name: Start kafka
  service:
    name: "kafka"
    state: restarted
    daemon_reload: yes
  become: true
  when:
    - inventory_hostname in groups['kafka']
    - kafka_enabled | bool