---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/zookeeper"
    state: directory
    mode: 0770
    recurse: yes
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ zookeeper_services }}"

- name: Setup zookeeper configuration
  template:
    src: "zookeeper.cfg.j2"
    dest: "{{ node_config_directory }}/zookeeper/zookeeper.cfg"
    mode: "0600"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool

- name: Configure zookeeper instance id
  template:
    src: "myid.j2"
    dest: "{{ node_config_directory }}/zookeeper/myid"
    mode: "0600"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
