- include_tasks: config.yml

- name: Install zookeeper-server
  yum:
    name: "{{ item.value.package_name }}"
    state: latest
  with_dict: "{{ zookeeper_services }}"

- name: Start zookeeper-server
  service:
    name: "zookeeper-server"
    state: started