- name: Install zookeeper-server
  yum:
    name: "{{ zookeeper_package_name }}"
    state: latest
  when:
    - inventory_hostname in groups['zookeeper']
    - zookeeper_enabled | bool

- include_tasks: config.yml

- name: Start zookeeper-server
  service:
    name: "zookeeper-server"
    state: restarted
    daemon_reload: yes
  when:
    - inventory_hostname in groups['zookeeper']
    - zookeeper_enabled | bool
