- hosts: mdp
  gather_facts: false
  roles:
    - environments/pre-deploy
    - environments/elasticsearch
    - environments/kafka
    - environments/zookeeper
    - mdp/pre-deploy
    - mdp/setup
  vars_files:
    - "group_vars/mdp/mdp_service_configs.yml"
