- name: install mysql client
  yum:
    name:  mysql-community-client
    state: latest

- name: ensure mdp config directory present
  file:
    path: "/etc/cron.daily"
    state: directory
    
- name: copy mysql backup script
  template:
    src: mysql_backup.sh.j2
    dest: "/etc/cron.daily/mysql_backup.sh"
    mode: u+x
  become: true

- name: setup cron job for mysql backup
  cron:
    name: "MySQL Backup"
    state: present
    user: root
    job: "/etc/cron.daily/mysql_backup.sh {{ groups['mysql'][0] }}"
    minute: "0"
    hour: "3"