---
- name: init yum server
  when: enable_yum|default(true)
  block:
    - name: check if yum repo directory exists
      register: yum_repo_exists
      stat:
        path: "{{ yum_repo_dir }}"
      when:
        - inventory_hostname in groups["yum_repo_server"]

    - name: instal dependencies
      yum:
        name: "{{ yum_repo_dir }}/{{ item }}"
      become: true
      with_items: "{{ yum_repo_dependencies }}"
      when:
        - inventory_hostname in groups["yum_repo_server"]
        - enable_yum|default(true) and yum_repo_exists.stat.exists

    - name: setup nginx
      block:
        - name: prepare nginx config file for yum
          file:
            path: /etc/nginx/conf.d/repo.conf
            state: touch
          when:
            - inventory_hostname in groups["yum_repo_server"]
            - enable_yum|default(true) and yum_repo_exists.stat.exists
          become: true          
        - name: configure nginx for yum
          when:
            - inventory_hostname in groups["yum_repo_server"]
            - enable_yum|default(true) and yum_repo_exists.stat.exists
          become: true
          blockinfile:
            path: /etc/nginx/conf.d/repo.conf
            block: |
              server {
                      listen {{ yum_repo_port }} default_server;
                      listen [::]:{{ yum_repo_port }} default_server;
                      server_name    {{ groups['yum_repo_server'][0] }};
                      root    {{ yum_repo_dir }};
                      autoindex    on;
                      charset    utf-8;
                      autoindex_localtime    on;
                      autoindex_exact_size    off;
              }
        - name: restart nginx service
          become: true
          when:
            - inventory_hostname in groups["yum_repo_server"]
            - enable_yum|default(true) and yum_repo_exists.stat.exists
          service:
            name: nginx
            state: restarted
    - name: init yum repo
      when:
        - inventory_hostname in groups["yum_repo_server"]
        - enable_yum|default(true) and yum_repo_exists.stat.exists
      shell: createrepo --workers 20 {{ yum_repo_dir }}

- name: clean yum repo configurations
  file:
    state: absent
    path: /etc/yum.repos.d
  become: true
  when:
    - enable_yum|default(true)

- name: create repo dir
  file:
    state: directory
    path: /etc/yum.repos.d/
  become: true
  when:
    - enable_yum|default(true)

- name: create mdp repo file
  yum_repository:
    name: "{{ yum_repo_name }}"
    description: MDP Repository
    baseurl: http://{{ groups['yum_repo_server'][0] }}:{{ yum_repo_port }}/
    gpgcheck: no
    enabled: yes
    priority: 1
  become: true
  when:
    - enable_yum|default(true)

- name: update yum cache
  shell: |
    yum clean all
    yum makecache
  become: true
  when:
    - enable_yum|default(true)
